MinGW + Qt requires libraries earlier for linker
Resolves Windows QtSVG build breaks undefined reference to
`__imp__ZN10QSvgWidgetC1ERK7QStringP7QWidget'.