Fix build with clang.
Clang complains about missing override declartions
```
src/gui/shell.h:21:8: fatal error: 'sizeHint' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
```
So make clang happy.

FIX